name: build and deploy
description: 'build and deploy'


inputs:
  unit_test_path:
    description: full path of the unit test script
    required: true
  unit_test_args:
    description: args for unit test script
    required: false

runs:
  using: "composite"
  steps:
    - name: set action env vars
      run: |
        echo "PATH_TO_ROOT=${{ github.action_path }}/../../.." >> $GITHUB_ENV
      shell: bash
    - name: install python and requirements
      uses: shay-demo/actions/actions/python/install_and_cache@main
    - name: get aws creds
      uses: shay-demo/actions/actions/unit_tests@main
      with:
        unit_test_path: ${{ inputs.unit_test_path }}
        unit_test_args: ${{ inputs.unit_test_args }}
