name: unit tests
description: 'unit tests'


inputs:
  unit_test_path:
    description: full path of the unit test script
    required: true
  unit_test_args:
    description: args for unit test script
    required: false


runs:
  using: "composite"
  steps:
    - name: set action env vars
      run: |
        echo "PATH_TO_ROOT=${{ github.action_path }}/../.." >> $GITHUB_ENV
      shell: bash
    - name: run unit tests
      run: $PATH_TO_ROOT/scripts/run_file.sh ${{ inputs.unit_test_path }} ${{ inputs.unit_test_args }}
      shell: bash

    